#+TITLE: org-tangle-dir

This package defines helper functions for dynamic =tangle-dir= property
resolution in Org Babel.  It evaluates sexps in =tangle-dir= property
values against a whitelist, walks the outline tree for inheritance, and
falls back to file-level =#+PROPERTY= when no heading-level property
exists.

* Installation

package-vc-install (Emacs 29+)
#+begin_src elisp
(package-vc-install "https://codeberg.org/useless-utils/org-tangle-dir")
(require 'org-tangle-dir)
#+end_src

use-package + package-vc-install (Emacs 29+)
#+begin_src elisp
(use-package org-tangle-dir
  :vc (:url "https://codeberg.org/useless-utils/org-tangle-dir"))
#+end_src

straight.el
#+begin_src elisp
(straight-use-package
 '(org-tangle-dir :type git :host codeberg :repo "useless-utils/org-tangle-dir"))
#+end_src

Elpaca
#+begin_src elisp
(elpaca (org-tangle-dir :host codeberg :repo "useless-utils/org-tangle-dir"))
#+end_src

Manual
#+begin_src elisp
(add-to-list 'load-path "/path/to/org-tangle-dir")
(require 'org-tangle-dir)
#+end_src

* Usage

** Property syntaxes

=org-tangle-dir= supports both drawer and file-level property syntax:

: #+PROPERTY: tangle-dir /default/path

or in a heading drawer (recommended):
#+begin_src text
:PROPERTIES:
:tangle-dir: /tmp/myproject
:END:
#+end_src

** Resolution order

When resolving =tangle-dir= for a heading:

1. Current heading's drawer (if non-empty)
2. Parent heading's drawer (walk up outline)
3. File-level =#+PROPERTY= (checked once at top of tree)
4. Error if nothing found

** Sexp evaluation

Property values that start with =(= are evaluated as Lisp.  Only whitelisted
functions may be used:

#+begin_src text
:PROPERTIES:
:tangle-dir: (expand-file-name "conf" (xdg-config-home))
:END:
#+end_src

- Allowed functions by default:
  + =org-tangle-dir-base=
  + =tdir-base=
  + =concat=
  + =expand-file-name=
  + =getenv=
  + =xdg-data-dirs=
  + =xdg-bin-home=
  + =xdg-cache-home=
  + =xdg-config-dirs=
  + =xdg-config-home=
  + =xdg-data-home=
  + =xdg-runtime-dir=

** Child-relative paths

Use =tdir-base= to build paths relative to the parent heading's
effective tangle dir:

#+begin_src org
,* Project
:PROPERTIES:
:tangle-dir: ~/projects/myapp
:END:
,** Config
:PROPERTIES:
:tangle-dir: (tdir-base "config")
:END:
#+end_src

** Src block usage

In a =:tangle= header of a source block, call =tdir= with the
filename:
#+begin_src org
:PROPERTIES:
:tangle-dir: ~/projects/myapp
:END:

,** Config
,#+begin_src conf :tangle (tdir "app.conf")
server.port: 8080
,#+end_src
#+end_src

** Example
#+begin_src org
,#+PROPERTY: tangle-dir ~/projects/myapp

,* Scripts
,#+begin_src sh :tangle (tdir "setup.sh")
#!/bin/bash
echo "running setup"
,#+end_src

,* Config
:PROPERTIES:
:tangle-dir: (expand-file-name "config" (xdg-config-home))
:END:
,#+begin_src yaml :tangle (tdir "app.yml")
app:
  name: myapp
,#+end_src
#+end_src

* Troubleshooting

** "circular :tangle-dir:" error

If a heading's =tangle-dir= uses =(tdir ...)= pointing to itself or a child,
circular resolution is detected and blocked.  Use =tdir-base= for parent-relative
paths instead.

** "unsafe form" error

Only functions in the whitelist may appear in sexp values.  This is a security
measure. Arbitrary Elisp cannot be evaluated from property values.

* COMMENT Notes
# [2023-05-19 Fri 23:48:32 -03]
# [2026-04-20 Mon 09:56:33 -03] @ak - pkg repo

- [[https://emacs.stackexchange.com/questions/19877/how-to-evaluate-elisp-code-contained-in-a-string/19878#19878][read - How to evaluate Elisp code contained in a string? - Emacs Stack Exchange]]
- [[https://emacs.stackexchange.com/questions/46479/how-to-set-a-tangled-parent-directory-for-each-subtree-in-org-mode/55859#55859][How to set a tangled parent directory for each subtree in org mode?]]
